mccr-gtk: fix comparison of unsigned
      CC       mui-page-basic.o
    mui-page-basic.c:249:91: error: comparison of unsigned expression < 0 is always false [-Werror,-Wtautological-compare]
        if (((data_size = strbin (str, (guint8 *)&self->priv->bdk, sizeof (self->priv->bdk))) < 0) ||
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
    1 error generated.

(cherry picked from commit 34844dcf4324f115c5172ece075817197b6f35b7)